CREATE DATABASE IF NOT EXISTS appdb;
USE appdb;
CREATE TABLE IF NOT EXISTS guestbook (
  id INT AUTO_INCREMENT PRIMARY KEY,
  isim VARCHAR(50),
  mesaj TEXT,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);